### ISSUE TITLE
Modelextractor.h

### ISSUE THREAD

**Issue by gbortignon** [gbortignon/QGen#1]
Verificare se possibile eliminare l'utilizzo di findcolumn nel metodo findAnomalSeq.

**Comment by boborbt** [comment]
L'unico punto in cui compare è commentato. L'hai commentato tu? La situazione iniziale qual era? era tutto decommentato o alcune parti erano commentate?

**Comment by gbortignon** [comment]
L'ho commentato solo per riuscire a compilarlo e verificare l'esistenza di
altri problemi. Il origine era tutto decommentato.
Il 22/apr/2015 14:41, "Roberto Esposito" <notifications@github.com> ha
scritto:
